### PR TITLE
  Added Auth Routes and fixed naming issues

### LINKED ISSUE #76: Server - Route - Auth Routes

### PR DESCRIPTION
**Pull request by th0s**
Closes #76

### CODE REVIEW

File: app/app.js [hunk 1]
```diff
@@ -12,12 +14,35 @@ app.use(express.static(path.join(__dirname, '..', 'public')));
...
 app.get('/api/entries', (req, res) => {
   Entry.find()
-  .then(function(entry) {
+  .then((entry) => {
     res.status(200).json(entry)
   })
-  // curl --request GET 'localhost:3000/api/formdata'
 })
 
+app.post('/api/users/login', (req, res) => {
```
Comment (atreidesend) [inline app/app.js]: add in auth middleware

File: app/app.js [hunk 2]
```diff
@@ -12,12 +14,35 @@ app.use(express.static(path.join(__dirname, '..', 'public')));
 
 app.get('/api/entries', (req, res) => {
```
Comment (atreidesend) [inline app/app.js]: add in auth middleware

File: app/app.js [hunk 3]
```diff
@@ -3,6 +3,8 @@ const path = require('path');
 const bodyParser = require('body-parser');
 const { User, Entry } = require('./models/models.js')
 const debug = process.env.DEBUG || false;
+const jwt = require('jsonwebtoken')
+const helpers = require('./auth/auth.js')
```
Comment (atreidesend) [inline app/app.js]: be explicit about what you're pulling in: { jwtAuth, pwdAuth, jwtOptions } = require....

that way you can use them on their own, and it also tells people what to look for in the import from file

**Review by atreidesend — CHANGES_REQUESTED** [review]

**Review by atreidesend — APPROVED** [review]
